urlcut/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('urlcutsite.urls', namespace='urlcutsite')),
]

urlcutsite/urls.py
from django.conf.urls import url

import urlcutsite.views

from django.conf import settings

MIN_LEN, MAX_LEN = settings.SHORT_URL_LENGTH_BOUNDS
 
urlpatterns = [
    # 'urlcutsite.views',
    url(r'^$', urlcutsite.views.index, name='home'),
    url(
        r'^!(?P<short_id>\w{'+str(MIN_LEN)+','+str(MAX_LEN)+'})$',
        urlcutsite.views.show_stats, name='showstats'
    ),
    url(
        r'^(?P<short_id>\w{'+str(MIN_LEN)+','+str(MAX_LEN)+'})$',
        urlcutsite.views.redirect_original, name='redirectoriginal'
    ),
    url(r'^makeshort/$', urlcutsite.views.shorten_url, name='shortenurl'),
]

urlcutsite/models.py
from random import randint, choice
import string

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

class Url(models.Model):
    __tablename__ = 'urls'

    def __str__(self):
        return self.url

    def _random_user():
        #pseude random workaround for order_by('?') slowness
        count = User.objects.all().count()
        if not count:
            return None
        while True:
            try:
                random_index = randint(0, count - 1)
                return User.objects.get(pk=random_index)
            except User.DoesNotExist:
                pass

    def _url_id():
        CHAR_SET = string.ascii_uppercase + string.digits + string.ascii_lowercase

        while True:
            length = randint(*settings.SHORT_URL_LENGTH_BOUNDS)
            short_id = ''.join(choice(CHAR_SET) for x in range(length))
            try:
                temp = Url.objects.get(pk=short_id)
            except Url.DoesNotExist:
                return short_id

    short_id = models.SlugField(primary_key=True, default=_url_id)
    url = models.URLField(max_length=2000, unique=True)
    counter = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now=True)
    submitter = models.ForeignKey(User, default=_random_user)

urlcutsite/views.py
import json

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.template.context_processors import csrf

from .models import Url


def index(request):
    return render(request, 'urlcutsite/index.html', csrf(request))
 
def redirect_original(request, short_id):
    url = get_object_or_404(Url, pk=short_id)
    url.counter += 1
    url.save()
    return HttpResponseRedirect(url.url)
 
def shorten_url(request):
    url_validator = URLValidator()
    req_url = request.POST.get("url")

    try:
        url_validator(req_url)
        url, _ = Url.objects.get_or_create(url=req_url)
        response_data = {'url': settings.SITE_URL + "/" + url.short_id}
    except ValidationError as e:
        response_data = {"error": str(e.message)}

    return HttpResponse(json.dumps(response_data),  content_type="application/json")

def show_stats(request, short_id):
    url = get_object_or_404(Url, pk=short_id)
    stats = {
        'url': url.url,
        'submitter': url.submitter.username,
        'counter': url.counter,
    }
    return render(
        request,
        'urlcutsite/stats.html',
        stats,
    )

urlcutsite/templates/urlcutsite/base.html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html>
   <head>
      <title>{% block title %}URLcut{% endblock %}</title>
      {% load staticfiles %}
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <meta name="viewport" content="width=device-width, initial-scale=1">
   </head>
   <body>
      <script type="text/javascript">
         $(function() {
	         $('#submitButton').click(function() {
		         $.ajax({
			         type: "POST",
			         url: "/makeshort/",
			         data: {
				         'url' : $('#url').val(),
				         'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
			         },
			         success: returnSuccess,
			         dataType: 'json'
		         });
	         });
         });
          
         function returnSuccess(data, textStatus, jqXHR) {
	         if(data.url) {
		         $('#url-result').text(data.url);
		         $('#url').val("");
	         } else {
		         $('#url-result').text(data.error); 
	         }
         }
      </script>
      <div id="wrap">
         <header>
            <h1><a href="{% url 'urlcutsite:home' %}">URLcut </a><small>cutting urls since 2017</small></h1>
         </header>
         <div id="content">
            {% block content %}
            {% endblock %}
         </div>
      </div>
   </body>
</html>

urlcutsite/templates/urlcutsite/index.html
{% extends "urlcutsite/base.html" %}
  
{% block title %}URLcut{% endblock %}
  
{% block content %}
  
<div class="panel panel-default">
    <div class="panel-body">
        <div class="col-sm-9">
            <input type="text" name="url" id="url" class="form-control input-sm" placeholder="http://www.google.pl" />
        </div>
        <div class="col-sm-3">
            {% csrf_token %}
            <p><button id="submitButton" class="btn btn-primary">Submit</button></p> 
        </div>
    </div>
    <div class="panel-footer"><span id="url-result">Enter the URL above and click submit!</span></div>
</div>
{% endblock %}

urlcutsite/templates/urlcutsite/stats.html
{% extends "urlcutsite/base.html" %}
  
{% block title %}URLcut{% endblock %}
  
{% block content %}
  
<div class="panel panel-default">
    <div class="panel-body">
        <div class="col-sm-3">
            <p>URL: <a href="{{ url }}">{{ url }}</a> </p>
            <p>Submitter: {{ submitter }}</p> 
            <p>Counter: {{ counter }} </p>
        </div>
    </div>
</div>
{% endblock %}